// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV_U-R35bICgIVUoo0FPO34Pes_vxrr6I',
    appId: '1:598636200191:web:57804ea9c836d82fe04cca',
    messagingSenderId: '598636200191',
    projectId: 'club-futbol-abh',
    authDomain: 'club-futbol-abh.firebaseapp.com',
    storageBucket: 'club-futbol-abh.appspot.com',
    measurementId: 'G-J7B0HV466K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1dYbGvRnioWXn4NlBhZrbT8V9OuDW6g',
    appId: '1:598636200191:android:1ffdd91318faf22ae04cca',
    messagingSenderId: '598636200191',
    projectId: 'club-futbol-abh',
    storageBucket: 'club-futbol-abh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy4P4Of4MO1WVpxh0qPl1T9KkeU_bpMmM',
    appId: '1:598636200191:ios:9043fa02de3c0942e04cca',
    messagingSenderId: '598636200191',
    projectId: 'club-futbol-abh',
    storageBucket: 'club-futbol-abh.appspot.com',
    iosBundleId: 'com.bitala.clubfutbol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy4P4Of4MO1WVpxh0qPl1T9KkeU_bpMmM',
    appId: '1:598636200191:ios:19ec08d13f9e1702e04cca',
    messagingSenderId: '598636200191',
    projectId: 'club-futbol-abh',
    storageBucket: 'club-futbol-abh.appspot.com',
    iosBundleId: 'com.example.flutterxsebas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV_U-R35bICgIVUoo0FPO34Pes_vxrr6I',
    appId: '1:598636200191:web:a0ee42f92eb3a249e04cca',
    messagingSenderId: '598636200191',
    projectId: 'club-futbol-abh',
    authDomain: 'club-futbol-abh.firebaseapp.com',
    storageBucket: 'club-futbol-abh.appspot.com',
    measurementId: 'G-6FFPNH4N9R',
  );
}
